# model args
model_name_or_path: ./model/base/Qwen2.5-VL-3B-Instruct/
model_revision: main
torch_dtype: bfloat16
# attn_implementation: flash_attention_2
bf16: true
tf32: true
output_dir: runs_grpo_ft/

# dataset arguments
dataset_id_or_path: ./ft_data.json

# Lora Arguments
# No LoRA is used here

# Training arguments
max_steps: 100
per_device_train_batch_size: 1
gradient_accumulation_steps: 4
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 5.0e-7 # 1.0e-6 as in the deepseek math paper 
lr_scheduler_type: cosine
warmup_ratio: 0.03
# GRPO specific parameters
beta: 0.001 # 0.04 as in the deepseek math paper
max_prompt_length: 256
max_completion_length: 512
num_generations: 8
use_vllm: false
# vllm_device: "cuda:3"
# vllm_gpu_memory_utilization: 0.5

# Logging arguments
logging_strategy: steps
logging_steps: 5
save_strategy: "steps"
save_steps: 50
seed: 5525
